# application.yml
server:
  port: 8080

spring:
  application:
    name: my-springboot-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,trace
  metrics:
    export:
      dynatrace:
        enabled: true
        api-token: dt0c01.6QLF7PO2ZGUMYUZNVDR4QSHE.E4DG3QYP7EF5NFT2QOPHDZ2IOLPZY7BBC6T7FPY6BNCRFKOITXH7VUZ6VJT2XAQO     # use env variable
        uri: https://xmz83804.live.dynatrace.com/api/v2/metrics/ingest
        device-id: ${HOSTNAME:local-dev}
        step: 1m
  tracing:
    sampling:
      probability: 1.0  # sample all traces in local dev/testing

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
