server:
  port: 9090

spring:
  application:
    name: my-springboot-app
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  metrics:
    export:
      dynatrace:
        enabled: true
        api-token: dt0c01.6QLF7PO2ZGUMYUZNVDR4QSHE.E4DG3QYP7EF5NFT2QOPHDZ2IOLPZY7BBC6T7FPY6BNCRFKOITXH7VUZ6VJT2XAQO
        uri: https://xmz83804.live.dynatrace.com/api/v2/metrics/ingest
        device-id: dev-${HOSTNAME:local}
        step: 30s

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.example: TRACE
